### ISSUE TITLE
SEO checklist

### ISSUE THREAD

**Issue by j3ko** [j3ko/commit-composer#24]
**Describe the solution you'd like**
- [ ] add page titles
- [ ] meta keywords
- [ ] improve [page speed](https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fcommit-composer.dev%2F)
- [ ] enhance [mobile](https://search.google.com/test/mobile-friendly) support
- [ ] increase write up content (ref. #22)
- [ ] support [structured data](https://search.google.com/test/rich-results)
